### Ver tdos
get http://localhost:4000/api/characters

### Ver por id 
get http://localhost:4000/api/characters/3


### Crear personaje
POST  http://localhost:4000/api/characters
Content-Type: application/json

{
    "name": "Piccolo",
    "ki": 200000,
    "race": "namekiano",
    "gender": "male",
    "description": "es un namekiano que se vuelve bueno"
}


###Actualizar
put http://localhost:4000/api/characters/2
Content-Type: application/json

{
    "name": "xxxx",
    "ki": 205670000,
    "race": "sayayin",
    "gender": "female"

}

###elimiar
DELETE http://localhost:4000/api/characters/2

