### Ver tdos
get http://localhost:4000/api/characters

### Ver por id 
get http://localhost:4000/api/characters/1


### Crear personaje

POST  http://localhost:4000/api/characters

###Actualizar
put http://localhost:4000/api/characters/1

###elimiar
DELETE http://localhost:4000/api/characters/1

